[package]
name = "vulkan-terminal"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = "0.38"
ash-window = "0.13"
winit = "0.30.11"
raw-window-handle = "0.6.2"
fontdue = "0.8"
bytemuck = { version = "1.0", features = ["derive"] }
memoffset = "0.9"
rusttype = "0.9.3"
image = "0.25.6"
