[package]
name = "vulkan-terminal"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = "0.37"
winit = "0.29"
raw-window-handle = "0.6"
fontdue = "0.8"
bytemuck = { version = "1.0", features = ["derive"] }
memoffset = "0.9"
